name: AWS-CICD 
on: [push]
jobs:
  interaction-with-aws:
    runs-on: ubuntu-latest # linux
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls


      - name: list s3 buckets
        uses: aws-actions/configure-aws-credentials@v4
        run: aws s3 ls